package algonquin.cst2335.groupproject.wenxinAPI;


import androidx.room.Database;

import androidx.room.RoomDatabase;
/**
 * Abstract database class for the recipe application using Room persistence library.
 * This class defines the database for the application with a list of its entities and the database version.
 * RoomDatabase provides direct access to the underlying database implementation but also validates your schema
 * once the application is compiled, ensuring that your application's data persistence layer is robust and efficient.
 *
 * <p>The database is configured to use the {@link Recipe} class as its entity. This means that the database
 * will contain a table based on the {@link Recipe} class, where each instance of {@link Recipe} will be persisted
 * in the database. The structure of the table is automatically derived from the fields of the {@link Recipe} class.</p>
 *
 * @see RoomDatabase
 * @author  Wenxin Li
 * @version 1.6
 * @since   2024-03-27
 */
@Database(entities = {Recipe.class}, version=1)
public abstract class RecipeDatabase  extends RoomDatabase {
    /**
     * Defines the DAO (Data Access Object) for accessing the {@link Recipe} table within the database.
     * This method serves as the primary interface for accessing stored {@link Recipe} entities within the
     * application's persistent data layer. Through the returned {@link RecipeDAO} instance, the application
     * can execute CRUD (Create, Read, Update, Delete) operations on the {@link Recipe} table.
     *
     * @return An implementation of the {@link RecipeDAO} interface, automatically generated by Room.
     */
    public abstract RecipeDAO cmDAO();
}
